### ISSUE TITLE
New/old issue of specifying a split scene output path within Python 

### ISSUE THREAD

**Issue by Mensen** [Breakthrough/PySceneDetect#303]
Apologies for raising a closed issue from the dead here, but the proposed solution (https://github.com/Breakthrough/PySceneDetect/issues/298#issuecomment-1312618866), doesn't work for my example.

```
>>> output_dir = r'F:\Gamepass_Clips'
>>> output_template = os.path.join(os.path.join(output_dir,"scene-$SCENE_NUMBER.mp4"))
>>> print(output_template)
F:\Gamepass_Clips\scene-$SCENE_NUMBER.mp4
>>> scenedetect.video_splitter.split_video_ffmpeg(video_file, scene_list,
...   output_file_template=output_template)
Error splitting video (ffmpeg returned 1).
1
```

My code differs from your example by using the ``os.path`` functions instead of writing the path in a regular string... but I have also tried that with no apparent difference.

I considered whether there were some potential write permissions that throws the error but when I do the actual ``scenedetect``, I also specify a ``stats_file_path`` in precisely the same way using the ``os.path`` method

Let me know if I should have simply raised another issue here, but considering the "solution" doesn't work, I figured it might be best to follow up here.

Thanks in advance for helping out one of your sponsors :)

_Originally posted by @Mensen in https://github.com/Breakthrough/PySceneDetect/issues/298#issuecomment-1317658389_

**Comment by Mensen** [comment]
Forward slashes also does not work.

```
scenedetect.video_splitter.split_video_ffmpeg(video_file, scene_list[0:2], 
...   output_file_template='F:/Gamepass_Clips/Clip-$SCENE_NUMBER.mp4')
Error splitting video (ffmpeg returned 1).
1
```

No issue when simply specifying a file name, but this then puts the files in the code directory which, when splitting 100s of scenes are _less than ideal_
```
scenedetect.video_splitter.split_video_ffmpeg(video_file, scene_list[0:2], 
...   output_file_template='Clip-$SCENE_NUMBER.mp4')
0
```

In the code snip above it refers to ``output_directory`` and not necessarily ``output_file_template`` so there seems to be an intermediate step between the ``split_video_ffmeg`` and the ``get_and_create_path`` code. Could the problem lie there?

For example in:
https://github.com/Breakthrough/PySceneDetect/blob/99a17b996bc471fca580149274dbaf886ab0e314/scenedetect/video_splitter.py#L234
That would certainly replace the double \\\ that ``os.path.join`` uses when combining paths to be os compatable.

And wouldn't the line:
https://github.com/Breakthrough/PySceneDetect/blob/99a17b996bc471fca580149274dbaf886ab0e314/scenedetect/video_splitter.py#L259
Replace the ":" with a ";" in the path I specified?

**Comment by Breakthrough** [comment]
This will be the final task to complete for the next release (v0.6.1) once the build is fixed.  Hoping to have that complete by no later than the end of this month.

**Comment by Breakthrough** [comment]
@Mensen can you confirm what version you were seeing this on?

The following code works for me locally on v0.6:

```
scenedetect.video_splitter.split_video_ffmpeg(
    "tests/resources/goldeneye.mp4", scenes,
output_file_template='C:/Users/Breakthrough/Git Repos/PySceneDetect/Clip-$START_TIME-$SCENE_NUMBER.mp4')
```

This *is* broken currently in v0.6.1 but I will make sure it's fixed before the release.  Just want to clarify though since with the latest stable code I don't think you should be getting this issue.  Thanks!

**Comment by Mensen** [comment]
@Breakthrough 
Indeed, I'm using v0.6.1 since there was another issue that was fixed for that version.

I'm happy to just transfer the output then for now and wait until a further release with the issues fixed.

**Comment by Breakthrough** [comment]
@Mensen v0.6.1 is now officially out, which includes the fix described here.  Let me know if you run into any other issues, thanks!

**Comment by gullalc** [comment]
Is this really fixed, because I am getting Error splitting video (ffmpeg returned 1) error still?

`split_video_ffmpeg('videos/sample_video.mp4', scene_list, show_progress=True)`

**Comment by Breakthrough** [comment]
@gullalc what do you get as the output if you set `show_output=True`?  Is there any way you can provide some more context to help debug?

Feel free to file a new issue if this is unrelated to the output file template.

**Comment by gullalc** [comment]
I found that it was a codec error and fixed it by overriding the arguments. Thanks for replying though.
